CREATE TABLE IF NOT EXISTS scan_uploads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    upload_id VARCHAR(64) NOT NULL UNIQUE,
    uploaded_at_epoch_ms BIGINT NULL,
    app_package VARCHAR(128) NULL,
    app_version_name VARCHAR(64) NULL,
    app_version_code BIGINT NULL,
    device_manufacturer VARCHAR(64) NULL,
    device_model VARCHAR(128) NULL,
    device_sdk_int INT NULL,
    predicted_species VARCHAR(128) NULL,
    predicted_cp INT NULL,
    predicted_hp INT NULL,
    predicted_caught_date_epoch_ms BIGINT NULL,
    predicted_is_shiny TINYINT(1) NOT NULL DEFAULT 0,
    predicted_is_shadow TINYINT(1) NOT NULL DEFAULT 0,
    predicted_is_lucky TINYINT(1) NOT NULL DEFAULT 0,
    predicted_has_costume TINYINT(1) NOT NULL DEFAULT 0,
    predicted_has_special_form TINYINT(1) NOT NULL DEFAULT 0,
    predicted_has_location_card TINYINT(1) NOT NULL DEFAULT 0,
    predicted_rarity_score INT NULL,
    predicted_rarity_tier VARCHAR(32) NULL,
    predicted_iv_estimate VARCHAR(64) NULL,
    raw_ocr_text MEDIUMTEXT NULL,
    pipeline_ms BIGINT NULL,
    explanations_json JSON NULL,
    breakdown_json JSON NULL,
    screenshot_relative_path VARCHAR(255) NULL,
    payload_json LONGTEXT NOT NULL,
    user_truth_species VARCHAR(128) NULL,
    user_truth_is_shiny TINYINT(1) NULL,
    user_truth_has_costume TINYINT(1) NULL,
    user_truth_form VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_scan_uploads_species_created (predicted_species, created_at),
    KEY idx_scan_uploads_created (created_at)
);

CREATE TABLE IF NOT EXISTS scan_feedback (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    upload_id VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_scan_feedback_upload (upload_id),
    KEY idx_scan_feedback_category (category)
);
