package com.pokerarity.scanner.service

import com.pokerarity.scanner.data.model.PokemonData
import com.pokerarity.scanner.data.model.RarityScore
import com.pokerarity.scanner.util.ocr.OcrDiagnosticsExporter

/**
 * Pure helper for safely attaching diagnostic metadata without polluting the
 * string-based rawOcrText pipeline with redundant or privacy-sensitive markers.
 */
object ScanRawOcrDiagnostics {

    /**
     * Attaches diagnostic metadata structurally while perfectly preserving the 
     * raw OCR string exactly as generated by upstream processors.
     */
    fun attach(
        pokemon: PokemonData,
        rarityScore: RarityScore,
        diagnosticBundle: OcrDiagnosticsExporter.Bundle?
    ): PokemonData {
        val ocrConfidenceReasons = ScanOcrConfidenceReasonFactory.create(pokemon, rarityScore)

        return pokemon.copy(
            ocrDiagnosticsDir = diagnosticBundle?.directory,
            ocrDiagnosticsFiles = diagnosticBundle?.files ?: emptyMap(),
            ocrConfidenceReasons = ocrConfidenceReasons
        )
    }
}
